# Generated by Django 3.0.5 on 2020-05-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_word_wordlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='author',
        ),
    ]
