# Generated by Django 3.0.5 on 2020-05-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_word_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='author',
        ),
        migrations.RemoveField(
            model_name='wordlist',
            name='terms',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='WordList',
        ),
    ]
