# Generated by Django 3.0.5 on 2020-05-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_word_wordlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sentence',
            field=models.CharField(max_length=300),
        ),
    ]
