# Generated by Django 3.0.5 on 2020-05-12 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200512_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
