# Generated by Django 3.0.5 on 2020-05-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='word',
        ),
    ]
