# Generated by Django 3.0.5 on 2020-05-23 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_quiz_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
