# Generated by Django 3.0.5 on 2020-05-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_quiz_date_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
