# Generated by Django 3.0.5 on 2020-05-23 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('testtaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wordlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.WordList')),
            ],
        ),
    ]
