# Generated by Django 3.0.5 on 2020-05-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='testtaker',
            new_name='author',
        ),
    ]
