# Generated by Django 3.0.5 on 2020-05-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200525_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
