# Generated by Django 3.0.5 on 2020-05-26 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_testtaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaker',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
