# Generated by Django 3.0.5 on 2020-05-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_testtaker_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaker',
            name='wrong_terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
