# Generated by Django 3.0.5 on 2020-05-30 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_testtaker_wrong_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaker',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 22, 35, 51, 474189, tzinfo=utc)),
        ),
    ]
