# Generated by Django 3.0.5 on 2020-05-30 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200530_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaker',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
