# Generated by Django 3.0.5 on 2020-06-03 17:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200530_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='worksheet_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
