# Generated by Django 3.0.5 on 2020-06-03 18:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_wordlist_worksheet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='worksheet_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
