# Generated by Django 3.0.5 on 2020-07-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200707_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Folder'),
        ),
    ]
