# Generated by Django 3.0.5 on 2020-07-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200707_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
